### ISSUE TITLE
코드 잘 봤습니다.

### ISSUE THREAD

**Issue by rae-han** [YeongseoYoon/pomodoro-app#2]
저도 useInterval과 useCounter로 커스텀 훅으로 빼고 싶었지만 만들기 급급해서 시도도 못했는데 다 하셨네요. 일단 코드 보면서 더 이해해봐야 할거 같긴한데 코드 잘 보겠습니다.

**Comment by YeongseoYoon** [comment]
저는 사실 래한님 코드가 너무 깔끔하게 분리돼있어서 보기 편안했어요! 저렇게 분리해야하는구나 많이 배웠습니다ㅋㅋㅋ이번 졸작때 컴포넌트 분리시에 참고하겠습니다
